# coding=utf-8
OPS = {
    "AndAnd" : " && ",
    "OrOr" : " || ",
    "Ampersand" : " & ",
    "Pipe" : " | ",
    "Comma" : " , ",
    "MinusMinus" : " -- ",
    "PlusPlus" : " ++ ",
    "DotDot" : " .. ",
    "ColonColon" : " :: ",
    "Dot" : " . ",
    "Exclaim" : " ! ",
    "Multiply" : " * ",
    "Divide" : " / ",
    "Rem" : " % ",
    "Plus" : " + ",
    "Minus" : " - ",
    "Equals" : " = ",
    "PlusEquals" : " += ",
    "MinusEquals" : " -= ",
    "MultiplyEquals" : " *= ",
    "DivideEquals" : " /= ",
    "RemainderEquals" : " %= ",
    "Redirection" : " > ",
    "RedirectInStd" : "",
    "Format" : " -f ",
    "Not" : " -not ",
    "Bnot" : " -bnot ",
    "And" : " -and ",
    "Or" : " -or ",
    "Xor" : " -xor ",
    "Band" : " -band ",
    "Bor" : " -bor ",
    "Bxor" : " -bxor ",
    "Join" : " -join",
    "Ieq" : " -ieq ",
    "Ine" : " -ine ",
    "Ige" : " -ige ",
    "Igt" : " -igt ",
    "Ilt" : " -ilt ",
    "Ile" : " -ile",
    "Ilike" : " -ilike ",
    "Inotlike" : " -inotlike ",
    "Imatch" : " -imatch ",
    "Inotmatch" : " -inotmatch ",
    "Ireplace" : " -ireplace ",
    "Icontains" : " -icontains ",
    "Inotcontains" : " -inotcontains ",
    "Iin" : " -iin ",
    "Inotin" : " -inotin ",
    "Isplit" : " -isplit ",
    "Ceq" : " -ceq ",
    "Cne" : " -cne ",
    "Cge" : " -cge ",
    "Cgt" : " -cgt ",
    "Clt" : " -clt ",
    "Cle" : " -cle ",
    "Clike" : " -clike ",
    "Cnotlike" : " -cnotlike ",
    "Cmatch" : " -cmatch ",
    "Cnotmatch" : " -cnotmatch ",
    "Creplace" : " -creplace ",
    "Ccontains" : " -ccontains ",
    "Cnotcontains" : " -cnotcontains ",
    "Cin" : " -cin ",
    "Cnotin" : " -cnotin ",
    "Csplit" : " -csplit ",
    "Is" : " -is ",
    "IsNot" : " -isnot ",
    "As" : " -as ",
    "PostfixPlusPlus": " ++ ",
    "PostfixMinusMinus" : " -- ",
    "Shl" : " -shl ",
    "Shr" : " -shr "
}

"""
OPS = {
    "Minus"     : " - ",
    "Plus"      : " + ",
    "Format"    : " -f ",
    "Equals"    : " = ",
    "PlusEquals": " += ",
    "PostfixPlusPlus": " ++ ",
    "Is"        : " -is ",
    "As"        : " -as ",
    "Ieq"       : " -eq ",
    "Ige"       : " -ge ",
    "Ile"       : " -le ",
    "Ine"       : " -ne ",
    "Bxor"      : " -bxor ",
    "Ireplace"  : " -replace ",
    "Join"      : " -join ",
    "Imatch"    : " -match ",
    "And"       : " -and ",
    "Or"        : " -or ",
    "Ilt"       : " -lt ",
}
"""